CREATE OR REPLACE DATABASE VM_DATABASE;

CREATE OR REPLACE SCHEMA VM_SCHEMA;


-- set up roles
CREATE OR REPLACE ROLE ANALYST;
CREATE OR REPLACE ROLE DEVELOPER;
CREATE OR REPLACE ROLE BI_ROLE;


CREATE OR REPLACE TABLE CREDIT_CARD_CUSTOMER
(
   id number,
   first_name string, 
   Last_name string,
   DoB string,
   creditcard string,
   PAN string,
   city string,
   country string
 );


 
INSERT INTO CREDIT_CARD_CUSTOMER VALUES
(1, 'Vishal', 'Kaushal','1990-01-01',468453451278,'ABCD','Delhi', 'India'),
(2, 'Rohit', 'Sharma','1991-01-01',346129428914,'CDEF','Mumbai', 'India'),
(3, 'Virat', 'Kohli','1992-01-01',456237318920,'DEFG','Bangalore', 'India'),
(4, 'Shami', 'Ahmad','1993-01-01',451672893013,'HIJK','Lucknow','India'),
(5, 'Jasprit', 'Bumrah','1994-01-01',246871249124,'LMNOP','Mumbai','India'),
(6, 'Axar' ,'Patel','1995-01-01',412916498123,'QRSTU','Ahemdabad','India');


SELECT * FROM CREDIT_CARD_CUSTOMER;


-- Set up masking policy--

CREATE OR REPLACE MASKING POLICY P1_MASKING AS (creditcard STRING) 
RETURNS STRING -> 
CASE 
   WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN creditcard
   WHEN CURRENT_ROLE() IN ('ANALYST') THEN REGEXP_REPLACE(creditcard, '^.{7}', '*******')
   WHEN CURRENT_ROLE() IN ('DEVELOPER') THEN '########'
   ELSE '***CAN NOT BE SEEN***'
END;

 CREATE OR REPLACE MASKING POLICY P2_MASKING AS (PAN STRING) RETURNS STRING ->
 CASE 
   WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN PAN
   WHEN CURRENT_ROLE() IN ('ANALYST') THEN REPLACE(PAN,SUBSTR(PAN,1,4),'$$$$')
   WHEN CURRENT_ROLE() IN ('DEVELOPER') THEN '@@@@@@@@'
   ELSE '***CAN NOT BEEN SEEN***'
   END;


-- FOR AN EXISTING TABLE ON VIEW, EXECUTE THE FOLLOWING STATEMENT--

ALTER TABLE IF EXISTS CREDIT_CARD_CUSTOMER MODIFY COLUMN creditcard SET MASKING POLICY P1_MASKING;

ALTER TABLE IF EXISTS CREDIT_CARD_CUSTOMER MODIFY COLUMN PAN SET MASKING POLICY P2_MASKING;

DESC TABLE CREDIT_CARD_CUSTOMER;


GRANT USAGE ON DATABASE VM_DATABASE TO ROLE ANALYST;
GRANT ALL ON SCHEMA VM_DATABASE.VM_SCHEMA TO ROLE ANALYST;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA VM_DATABASE.VM_SCHEMA TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST;


GRANT USAGE ON DATABASE VM_DATABASE TO ROLE DEVELOPER;
GRANT ALL ON SCHEMA VM_DATABASE.VM_SCHEMA TO ROLE DEVELOPER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA VM_DATABASE.VM_SCHEMA TO ROLE DEVELOPER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DEVELOPER;


GRANT USAGE ON DATABASE VM_DATABASE TO ROLE BI_ROLE;
GRANT ALL ON SCHEMA VM_DATABASE.VM_SCHEMA TO ROLE BI_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA VM_DATABASE.VM_SCHEMA TO ROLE BI_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE BI_ROLE;



-- Validating policies

USE ROLE ACCOUNTADMIN;
SELECT * FROM VM_DATABASE.VM_SCHEMA.CREDIT_CARD_CUSTOMER;

USE ROLE ANALYST;
SELECT * FROM VM_DATABASE.VM_SCHEMA.CREDIT_CARD_CUSTOMER;

USE ROLE DEVELOPER;
SELECT * FROM VM_DATABASE.VM_SCHEMA.CREDIT_CARD_CUSTOMER;  


USE ROLE BI_ROLE;
SELECT * FROM VM_DATABASE.VM_SCHEMA.CREDIT_CARD_CUSTOMER; 





--How we can remove the masking policy--

| alter table if exists CREDIT_CARD_CUSTOMER modify column creditcard unset masking policy;

  alter table if exists CREDIT_CARD_CUSTOMER modify column PAN unset masking policy;